# =====================================================
#       _           _                      _
#   ___| |_   _ ___| |_ ___ _ __ _ __ ___ | | ___  ___
#  / __| | | | / __| __/ _ \ '__| '__/ _ \| |/ _ \/ __|
# | (__| | |_| \__ \ ||  __/ |  | | | (_) | |  __/\__ \
#  \___|_|\__,_|___/\__\___|_|  |_|  \___/|_|\___||___/
#                                          clusterroles
# =====================================================
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cic-k8-role
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "ingresses", "pods", "secrets"]
    verbs: ["*"]

  - apiGroups: ["extensions"]
    resources: ["ingresses", "ingresses/status"]
    verbs: ["*"]
# =====================================================
#            _      _     _           _ _
#  _ __ ___ | | ___| |__ (_)_ __   __| (_)_ __   __ _ ___
# | '__/ _ \| |/ _ \ '_ \| | '_ \ / _` | | '_ \ / _` / __|
# | | | (_) | |  __/ |_) | | | | | (_| | | | | | (_| \__ \
# |_|  \___/|_|\___|_.__/|_|_| |_|\__,_|_|_| |_|\__, |___/
#                                   rolebindings|___/
# =====================================================
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cic-k8-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cic-k8-role
subjects:
- kind: ServiceAccount
  name: cic-k8-role
  namespace: default
apiVersion: rbac.authorization.k8s.io/v1
# =====================================================
#                      _                                          _
#  ___  ___ _ ____   _(_) ___ ___  __ _  ___ ___ ___  _   _ _ __ | |_ ___
# / __|/ _ \ '__\ \ / / |/ __/ _ \/ _` |/ __/ __/ _ \| | | | '_ \| __/ __|
# \__ \  __/ |   \ V /| | (_|  __/ (_| | (_| (_| (_) | |_| | | | | |_\__ \
# |___/\___|_|    \_/ |_|\___\___|\__,_|\___\___\___/ \__,_|_| |_|\__|___/
#                                                          serviceaccounts
# =====================================================
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cic-k8-role
  namespace: default
---
# ====================Citrix Ingress Controller  =================================
#                  _
#  _ __   ___   __| |___
# | '_ \ / _ \ / _` / __|
# | |_) | (_) | (_| \__ \
# | .__/ \___/ \__,_|___/
# |_|                pods
# =====================================================================================
apiVersion: v1
kind: Pod
metadata:
  name: cic-k8s-ingress-controller
  labels:
    app: cic-k8s-ingress-controller
spec: 
      serviceAccountName: cic-k8-role
      containers:
      - name: cic-k8s-ingress-controller
        image: "gcr.io/citrix-k8s-ingress-controller/citrix-ingress-controller:latest"
        env:
        # Set NetScaler NSIP/SNIP, SNIP in case of HA (mgmt has to be enabled) 
        - name: "NS_IP"
          value: "x.x.x.x"
        # Set username for Nitro
         - name: "NS_USER"
          valueFrom:
           secretKeyRef:
            name: nslogin
            key: username
        # Set user password for Nitro
        - name: "NS_PASSWORD"
          valueFrom:
           secretKeyRef:
            name: nslogin
            key: password
        # Set log level
        - name: "EULA"
          value: "yes"
